<?php

return [
    "GSAP are the initials for GreenSock Animation Platform. It is a library of plugins in Javascript where the goal is to animate elements without difficulties, it can be elements of your code like divs, simple images (png, jpeg, webp type) or more advanced (SVG). <br /><br /> In this course, we will use the DrawSVG plugin, which as its name suggests, will <b><u>draw</u></b> SVGs. This is the primary function of this plugin. We will also use the ScrollTrigger plugin, which will allow us to interact with the scroll of our site. Once these two plugins are combined, your site will be transformed, it will no longer be static, but dynamic!" => "GSAP sont les initiales pour GreenSock Animation Platform. C’est une librairie de plugins en Javascript où est le but est d’animer des éléments sans difficultés, cela peut être des éléments de votre code comme des div, images simples (type png, jpeg, webp) ou plus avancé (SVG). <br /><br /> Dans ce cours, nous allons utiliser le plugin DrawSVG, qui comme son nom l’indique, permettra de <b><u>dessiner</u></b> des SVG. C’est la fonction primaire de ce plugin. Nous allons également utiliser le plugin ScrollTrigger, qui nous permettra d’interagir avec le scroll de notre site. Une fois ces deux plugins combinés, votre site sera transformé, il ne sera plus statique, mais dynamique !",
    "What is GSAP?" => "Qu’est-ce que GSAP ?",
    "GSAP manipulates CSS properties" => "GSAP manipule les propriétés CSS",
    "The animation boils down to changing the value of the property multiple times per second, giving something the appearance of a movement, a fade, a rotation... GSAP captures the start and end values ​​and calculates the median value 60 times per second. It is what is called interpolation." => "L'animation se résume par modifier la valeur de la propriété plusieurs fois par seconde, donnant à quelque chose l'apparence d'un mouvement, d'un fondu, d'une rotation... GSAP saisit les valeurs de début et de fin et calcule la valeur médiane 60 fois par seconde. C'est ce qu'on appelle l'interpolation.",
    "For example, to hide an element on the page, GSAP gradually changes the opacity of the element from 1 to 0. The job of animating a web page is to break down a property and change it by its speed or rhythm." => "Par exemple, pour masquer un élément de la page, GSAP modifie progressivement l'opacité de l'élément de 1 à 0. Le travail d'animation d'une page Web consiste à décomposer une propriété et à la modifier par sa vitesse ou son rythme.",
    "Now that we know why, you need to use GSAP, let's move on to the next part!" => "Maintenant que nous savons pourquoi, vous devez utiliser GSAP, dirigeons nous vers la prochaine partie !",
    "Next" => "Suivant",
    "Getting started" => "Commencer",
    "Previous" => "Précédent",
];